using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class GoDown2 : MonoBehaviour {

	//bool didPlayerWin = false;
	public Text captureMessage;
	public Transform player;
	public float placementReference = 5f;
	public GameObject textBox;
	// Use this for initialization
	void Start () {

	}

	// Update is called once per frame
	void Update () {
		if ((player.position - transform.position).magnitude < placementReference) {
			enableTextBox();
			captureMessage.text = "Press [SPACE] to go down the stairs.";
			if (Input.GetKeyDown (KeyCode.Space)) {
				player.position = new Vector3 (219, -4, 1);
			}


		} else {
			disableTextBox();
			captureMessage.text = "";
		}



	}
	public void enableTextBox(){
		textBox.SetActive (true);
	}
	public void disableTextBox(){
		textBox.SetActive (false);

	}
}
